# Generated by Django 5.2.1 on 2025-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Academico", "0002_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
